using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ProjectEuler.Util;

/*
Pentagon numbers
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */

namespace ProjectEuler
{
	class P044
	{
		public P044 ()
		{
			var pent = new PentagonalNumbers ();

			var best = ulong.MaxValue;
			var prev = 0ul;

			foreach (var a in PentagonalNumbers.Pentagons ()) {
				if (a - prev > best) {
					// Cannot improve further
					break;
				}
				foreach (var b in PentagonalNumbers.Pentagons ().TakeWhile (b => b < a)) {
					var d = a - b;
					if (pent.IsPent (a + b) && pent.IsPent (d)) {
						if (d < best) {
							best = d;
							Console.WriteLine ("New best " + best + " from " + a + ", " + b);
						}
					}
				}
			}
		}
	}
}
